### ISSUE TITLE
Documents and Tutorials for distributed Optimal Power Flow

### ISSUE THREAD

**Issue by Vurgit** [alexe15/ALADIN.m#115]
Hi Alex, the optimal power flow folder in the example folder has two examples of distributed OPF, but they lack documents or tutorials. Despite that they can run without errors, I dont know how to see the values of variables, say, phase angles θ, voltage magnitudes V, active power P and reactive power Q of each buses after optimization, and I dont know how to apply the ALADIN method to other cases inherited in matpower. Could you please help me with these problems? Thank you for your patience.

**Comment by alexe15** [comment]
Hi Vurgit, thanks for your question! You can find the optimal solution for each subsystem in the `res_ALADIN.xxOpt` cell, where each cell entry is one subsystem. The partitioning of the optimal solution is `x_i = (θ_i v_i p_i q_i)^T`, where p and q denote the power generated at each node. For applying ALADIN alpha to other cases, you would need code, which generates objective and constraint functions. We have such a code but at the moment it is not documented and would need a bit of refactoring for publishing it. But you can have a look in the [rapidPF](https://kit-iai.github.io/rapidPF/) toolbox for an example how to set up these functions for power flow problems.
