### ISSUE TITLE
Can ALADIN be used for solving mixed integer linear programming problems with solvers like Bonmin?

### ISSUE THREAD

**Issue by zhengzhuang3** [alexe15/ALADIN.m#118]
I have a multi-agent system and each agent solves a mixed integer linear programming model. I am wondering whether these MILPs can be distributionally optimized by ALADIN. Thanks!

**Comment by alexe15** [comment]
Dear zhengzhuang3, at the moment ALADIN-α supports continuous variables only. An extensions to mixed integer problems is currently not planned.
