### ISSUE TITLE
sol_ALADIN Error

### ISSUE THREAD

**Issue by kristianrandell** [alexe15/ALADIN.m#119]
Hi,

I keep on getting sol_ALADIN error and unrecognized function or variable 'setDefaultOpts'
I am trying to run the examples.
Please advise.
![error](https://user-images.githubusercontent.com/94063159/141138163-c1c21e2e-6668-48d4-9d9f-a56c8b3ee0dd.PNG)

**Comment by alexe15** [comment]
The 'setDefaultOpts' function is available in the `/scr/extensions` folder. It should work if you add the `/src` folder with all subfolders to your MATLAB path.
